/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unab.edu.sv.Formularios;

import com.unab.edu.sv.DAO.ClsPersona;
import com.unab.edu.sv.Entidades.Personas;
import com.unab.edu.sv.mysql.conexionBD;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 14-ck0013lab
 */
public class fPersonas extends javax.swing.JInternalFrame {

    /**
     * Creates new form fPersonas
     */
    public fPersonas() {
        initComponents();
        CargarTabla();
        ajustartabla();
        limpiar();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        lectura();
        tbPersonas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
      

    }

    public void ajustartabla() {
        // Ocultar la columna del ID de la pelicula
        tbPersonas.getColumnModel().getColumn(0).setMaxWidth(0);
        tbPersonas.getColumnModel().getColumn(0).setMinWidth(0);
        tbPersonas.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        tbPersonas.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);

        //Centrar en texto del encabezado de la tabla
        DefaultTableCellRenderer render = (DefaultTableCellRenderer) tbPersonas.getTableHeader().getDefaultRenderer();
        render.setHorizontalAlignment(JLabel.CENTER);
        DefaultTableCellRenderer al = new DefaultTableCellRenderer();
        al.setHorizontalAlignment(SwingConstants.CENTER);
        tbPersonas.getColumnModel().getColumn(1).setCellRenderer(al);
        tbPersonas.getColumnModel().getColumn(2).setCellRenderer(al);
        tbPersonas.getColumnModel().getColumn(3).setCellRenderer(al);

    }

    void CargarTabla() {
        String TITULOS[] = {"ID", "Nombres", "Apellidos", "DUI"};
        ClsPersona per = new ClsPersona();
        DefaultTableModel model = new DefaultTableModel(null, TITULOS);
        ArrayList<Personas> person = per.ListaPersonas();
        String filas[] = new String[4];
        for (var i : person) {
            filas[0] = String.valueOf(i.idPersona);
            filas[1] = i.getNombres();
            filas[2] = i.getApellidos();
            filas[3] = i.getDUI();
            model.addRow(filas);
        }
        tbPersonas.setModel(model);

    }

    public void limpiar() {
        txtApellido.setText("");
        txtDui.setText("");
        txtNombres.setText("");
        estado = 0;
        id = 0;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        panelCRUD = new javax.swing.JPanel();
        lblNombres = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblDUI = new javax.swing.JLabel();
        txtDui = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        lblEncabezado = new javax.swing.JLabel();
        btnLectura = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPersonas = new javax.swing.JTable();

        panelFondo.setBackground(new java.awt.Color(0, 0, 0));

        panelCRUD.setBackground(new java.awt.Color(153, 255, 204));
        panelCRUD.setOpaque(false);

        lblNombres.setBackground(new java.awt.Color(51, 51, 51));
        lblNombres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombres.setForeground(new java.awt.Color(255, 255, 255));
        lblNombres.setText("NOMBRES");

        txtNombres.setBackground(new java.awt.Color(0, 0, 0));
        txtNombres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNombres.setForeground(new java.awt.Color(255, 255, 255));
        txtNombres.setBorder(null);
        txtNombres.setCaretColor(new java.awt.Color(255, 255, 255));

        lblApellidos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblApellidos.setForeground(new java.awt.Color(255, 255, 255));
        lblApellidos.setText("APELLIDOS");

        txtApellido.setBackground(new java.awt.Color(0, 0, 0));
        txtApellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(255, 255, 255));
        txtApellido.setBorder(null);
        txtApellido.setCaretColor(new java.awt.Color(255, 255, 255));

        lblDUI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDUI.setForeground(java.awt.Color.white);
        lblDUI.setText("DUI");

        txtDui.setBackground(new java.awt.Color(0, 0, 0));
        txtDui.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDui.setForeground(new java.awt.Color(255, 255, 255));
        txtDui.setBorder(null);
        txtDui.setCaretColor(new java.awt.Color(255, 255, 255));

        btnGuardar.setBackground(new java.awt.Color(255, 255, 102));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setBorderPainted(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 255, 102));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setBorderPainted(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(255, 255, 102));
        btnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setBorderPainted(false);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCRUDLayout = new javax.swing.GroupLayout(panelCRUD);
        panelCRUD.setLayout(panelCRUDLayout);
        panelCRUDLayout.setHorizontalGroup(
            panelCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCRUDLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblNombres)
                    .addComponent(lblApellidos)
                    .addComponent(lblDUI))
                .addGap(175, 175, 175))
            .addGroup(panelCRUDLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(panelCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombres)
                    .addComponent(txtApellido)
                    .addComponent(txtDui)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCRUDLayout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar)
                        .addGap(18, 18, 18))
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        panelCRUDLayout.setVerticalGroup(
            panelCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCRUDLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblNombres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblApellidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDUI)
                .addGap(9, 9, 9)
                .addComponent(txtDui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(panelCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnEliminar)
                    .addComponent(btnGuardar))
                .addContainerGap())
        );

        lblEncabezado.setFont(new java.awt.Font("Algerian_R", 1, 60)); // NOI18N
        lblEncabezado.setForeground(new java.awt.Color(255, 255, 255));
        lblEncabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEncabezado.setText("PERSONAS");

        btnLectura.setForeground(new java.awt.Color(204, 255, 255));
        btnLectura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/lectura.png"))); // NOI18N
        btnLectura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLectura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLecturaMouseClicked(evt);
            }
        });

        tbPersonas = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int collIndex){
                return false;
            }
        };
        tbPersonas.setBackground(new java.awt.Color(0, 0, 0));
        tbPersonas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbPersonas.setForeground(new java.awt.Color(255, 255, 255));
        tbPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbPersonas.setGridColor(new java.awt.Color(0, 0, 0));
        tbPersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPersonasMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbPersonasMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbPersonas);

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(lblEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
                        .addGap(177, 177, 177)
                        .addComponent(btnLectura)
                        .addContainerGap())
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelCRUD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblEncabezado))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLectura)))
                .addGap(42, 42, 42)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(panelCRUD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 163, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int estado = 0;
    int id = 0;

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (estado == 0) {

            Personas per = new Personas();
            per.setNombres(txtNombres.getText());
            per.setApellidos(txtApellido.getText());
            per.setDUI(txtDui.getText());
            ClsPersona cls = new ClsPersona();
            if (txtNombres.getText() == "" || txtNombres.getText().isEmpty() || txtNombres.getText() == null) {
                JOptionPane.showMessageDialog(null, "Es necesario agregar Nombre");
                txtNombres.requestFocus();
            } else if (txtApellido.getText() == "" || txtApellido.getText().isEmpty() || txtApellido.getText() == null) {
                JOptionPane.showMessageDialog(null, "Es necesario agregar Apellido");
                txtApellido.requestFocus();
            } else if (txtDui.getText() == "" || txtDui.getText().isEmpty() || txtDui.getText() == null) {
                JOptionPane.showMessageDialog(null, "Es necesario agregar Dui");
                txtDui.requestFocus();
            } else {
                cls.AgregarPersona(per);
                limpiar();
                CargarTabla();
                ajustartabla();
            }
        } else if (estado == 1) {
            Personas pers = new Personas();
            pers.setIdPersona(id);
            pers.setNombres(txtNombres.getText());
            pers.setApellidos(txtApellido.getText());
            pers.setDUI(txtDui.getText());
            ClsPersona cls = new ClsPersona();
            if (txtNombres.getText() == "" || txtNombres.getText().isEmpty() || txtNombres.getText() == null) {
                JOptionPane.showMessageDialog(null, "Es necesario agregar Nombre");
                txtNombres.requestFocus();
            } else if (txtApellido.getText() == "" || txtApellido.getText().isEmpty() || txtApellido.getText() == null) {
                JOptionPane.showMessageDialog(null, "Es necesario agregar Apellido");
                txtApellido.requestFocus();
            } else if (txtDui.getText() == "" || txtDui.getText().isEmpty() || txtDui.getText() == null) {
                JOptionPane.showMessageDialog(null, "Es necesario agregar Dui");
                txtDui.requestFocus();
            } else {
                cls.ActualizarPersona(pers);
                CargarTabla();
                ajustartabla();
            }
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        Personas p = new Personas();
        ClsPersona cls = new ClsPersona();
        p.setIdPersona(id);
        cls.EliminarPersonas(p);
        CargarTabla();
        ajustartabla();
        limpiar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnLecturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLecturaMouseClicked
        // TODO add your handling code here:
        lectura();
    }//GEN-LAST:event_btnLecturaMouseClicked

    private void tbPersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPersonasMouseClicked

    }//GEN-LAST:event_tbPersonasMouseClicked

    private void tbPersonasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPersonasMouseReleased
        // TODO add your handling code here:
     int fila = tbPersonas.getSelectedRow();
        id = Integer.valueOf(String.valueOf(tbPersonas.getValueAt(fila, 0)));
        String nombre = String.valueOf(tbPersonas.getValueAt(fila, 1));
        String apellido = String.valueOf(tbPersonas.getValueAt(fila, 2));
        String Dui = String.valueOf(tbPersonas.getValueAt(fila, 3));
        estado = 1;
        txtApellido.setText(apellido);
        txtDui.setText(Dui);
        txtNombres.setText(nombre);  
    }//GEN-LAST:event_tbPersonasMouseReleased
 
        public int edicion = 0;

    void lectura() {
        if (edicion == 0) {
            panelCRUD.setVisible(false);
            btnLectura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/editar.png")));
            edicion = 1;
        } else {
            btnLectura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/lectura.png")));
            panelCRUD.setVisible(true);
            edicion = 0;
        }
        limpiar();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel btnLectura;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblDUI;
    private javax.swing.JLabel lblEncabezado;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JPanel panelCRUD;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JTable tbPersonas;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDui;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
