/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unab.edu.sv.Formularios;

import java.awt.AWTEventMulticaster;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import jdk.jfr.Event;

/**
 *
 * @author Rafael
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(this);
    }
    public int id;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        panelBarra = new javax.swing.JPanel();
        btnCerrarMenu = new javax.swing.JLabel();
        btnOcultar = new javax.swing.JLabel();
        btncerrar = new javax.swing.JLabel();
        btnMinimizar = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        panelBotones = new javax.swing.JPanel();
        btnProveedores = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnPeliculas = new javax.swing.JButton();
        btnRoles = new javax.swing.JButton();
        btnPersonas = new javax.swing.JButton();
        btnSalas = new javax.swing.JButton();
        btnHorarios = new javax.swing.JButton();
        panelLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblSalir = new javax.swing.JLabel();
        panelBotonesFacturas = new javax.swing.JPanel();
        btnCarteleras = new javax.swing.JButton();
        btnFacturar = new javax.swing.JButton();
        panelcontenedor = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(1158, 631));
        setUndecorated(true);

        panelFondo.setBackground(new java.awt.Color(0, 0, 0));
        panelFondo.setMaximumSize(new java.awt.Dimension(0, 0));
        panelFondo.setMinimumSize(new java.awt.Dimension(0, 0));

        panelBarra.setBackground(new java.awt.Color(215, 172, 33));
        panelBarra.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        panelBarra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelBarraMouseDragged(evt);
            }
        });
        panelBarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelBarraMousePressed(evt);
            }
        });

        btnCerrarMenu.setBackground(new java.awt.Color(204, 0, 0));
        btnCerrarMenu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCerrarMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCerrarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/menu.png"))); // NOI18N
        btnCerrarMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMenuMouseClicked(evt);
            }
        });

        btnOcultar.setBackground(new java.awt.Color(204, 0, 0));
        btnOcultar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnOcultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnOcultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/minimizar.png"))); // NOI18N
        btnOcultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOcultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOcultarMouseClicked(evt);
            }
        });

        btncerrar.setBackground(new java.awt.Color(204, 0, 0));
        btncerrar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btncerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btncerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/cerca.png"))); // NOI18N
        btncerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncerrarMouseClicked(evt);
            }
        });

        btnMinimizar.setBackground(new java.awt.Color(204, 0, 0));
        btnMinimizar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/maximizar.png"))); // NOI18N
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        lblID.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        javax.swing.GroupLayout panelBarraLayout = new javax.swing.GroupLayout(panelBarra);
        panelBarra.setLayout(panelBarraLayout);
        panelBarraLayout.setHorizontalGroup(
            panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraLayout.createSequentialGroup()
                .addComponent(btnCerrarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addComponent(btnOcultar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );
        panelBarraLayout.setVerticalGroup(
            panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCerrarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBarraLayout.createSequentialGroup()
                .addGroup(panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOcultar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelMenu.setBackground(new java.awt.Color(215, 172, 33));

        panelBotones.setBackground(new java.awt.Color(215, 172, 33));
        panelBotones.setOpaque(false);

        btnProveedores.setBackground(new java.awt.Color(0, 0, 0));
        btnProveedores.setFont(new java.awt.Font("Algerian_R", 1, 18)); // NOI18N
        btnProveedores.setForeground(new java.awt.Color(255, 255, 255));
        btnProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/producto.png"))); // NOI18N
        btnProveedores.setText("PROVEEDORES");
        btnProveedores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProveedores.setPreferredSize(new java.awt.Dimension(267, 30));
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });

        btnProductos.setBackground(new java.awt.Color(0, 0, 0));
        btnProductos.setFont(new java.awt.Font("Algerian_R", 1, 18)); // NOI18N
        btnProductos.setForeground(new java.awt.Color(255, 255, 255));
        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/caja.png"))); // NOI18N
        btnProductos.setText("PRODUCTOS");
        btnProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProductos.setPreferredSize(new java.awt.Dimension(267, 30));
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });

        btnPeliculas.setBackground(new java.awt.Color(0, 0, 0));
        btnPeliculas.setFont(new java.awt.Font("Algerian_R", 1, 18)); // NOI18N
        btnPeliculas.setForeground(new java.awt.Color(255, 255, 255));
        btnPeliculas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/camara-de-video.png"))); // NOI18N
        btnPeliculas.setText("PELICULA");
        btnPeliculas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnPeliculas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeliculasActionPerformed(evt);
            }
        });

        btnRoles.setBackground(new java.awt.Color(0, 0, 0));
        btnRoles.setFont(new java.awt.Font("Algerian_R", 1, 18)); // NOI18N
        btnRoles.setForeground(new java.awt.Color(255, 255, 255));
        btnRoles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/admin-con-ruedas-dentadas.png"))); // NOI18N
        btnRoles.setText("ROLES");
        btnRoles.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnRoles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRoles.setPreferredSize(new java.awt.Dimension(267, 30));
        btnRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRolesActionPerformed(evt);
            }
        });

        btnPersonas.setBackground(new java.awt.Color(0, 0, 0));
        btnPersonas.setFont(new java.awt.Font("Algerian_R", 1, 18)); // NOI18N
        btnPersonas.setForeground(new java.awt.Color(255, 255, 255));
        btnPersonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/agregue-el-simbolo-de-la-interfaz-de-personas-de-la-persona-negra-de-cerca-con-el-signo-mas-en-un-circulo-pequeno.png"))); // NOI18N
        btnPersonas.setText("PERSONAS");
        btnPersonas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnPersonas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPersonas.setPreferredSize(new java.awt.Dimension(267, 30));
        btnPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonasActionPerformed(evt);
            }
        });

        btnSalas.setBackground(new java.awt.Color(0, 0, 0));
        btnSalas.setFont(new java.awt.Font("Algerian_R", 1, 18)); // NOI18N
        btnSalas.setForeground(new java.awt.Color(255, 255, 255));
        btnSalas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/boton-salir-a-la-aplicacion.png"))); // NOI18N
        btnSalas.setText("SALAS");
        btnSalas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnSalas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalas.setPreferredSize(new java.awt.Dimension(267, 30));
        btnSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalasActionPerformed(evt);
            }
        });

        btnHorarios.setBackground(new java.awt.Color(0, 0, 0));
        btnHorarios.setFont(new java.awt.Font("Algerian_R", 1, 18)); // NOI18N
        btnHorarios.setForeground(new java.awt.Color(255, 255, 255));
        btnHorarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/paso-del-tiempo.png"))); // NOI18N
        btnHorarios.setText("HORARIOS");
        btnHorarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnHorarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHorarios.setPreferredSize(new java.awt.Dimension(267, 30));
        btnHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHorariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(btnProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(btnRoles, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(btnPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(btnSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(btnHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(btnPeliculas, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesLayout.createSequentialGroup()
                .addComponent(btnPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRoles, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(btnHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        panelLogo.setOpaque(false);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/logoPrincipalfrm.png"))); // NOI18N
        lblLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoMouseClicked(evt);
            }
        });

        lblSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/cerrar-sesion.png"))); // NOI18N
        lblSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelLogoLayout = new javax.swing.GroupLayout(panelLogo);
        panelLogo.setLayout(panelLogoLayout);
        panelLogoLayout.setHorizontalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoLayout.createSequentialGroup()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(lblSalir)
                .addContainerGap())
        );
        panelLogoLayout.setVerticalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSalir, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        panelBotonesFacturas.setOpaque(false);

        btnCarteleras.setBackground(new java.awt.Color(0, 0, 0));
        btnCarteleras.setFont(new java.awt.Font("Algerian_R", 1, 18)); // NOI18N
        btnCarteleras.setForeground(new java.awt.Color(255, 255, 255));
        btnCarteleras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/cartelera.png"))); // NOI18N
        btnCarteleras.setText("CARTELERAS");
        btnCarteleras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnCarteleras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCarteleras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCartelerasActionPerformed(evt);
            }
        });

        btnFacturar.setBackground(new java.awt.Color(0, 0, 0));
        btnFacturar.setFont(new java.awt.Font("Algerian_R", 1, 18)); // NOI18N
        btnFacturar.setForeground(new java.awt.Color(255, 255, 255));
        btnFacturar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/facturas.png"))); // NOI18N
        btnFacturar.setText("Facturar");
        btnFacturar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnFacturar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesFacturasLayout = new javax.swing.GroupLayout(panelBotonesFacturas);
        panelBotonesFacturas.setLayout(panelBotonesFacturasLayout);
        panelBotonesFacturasLayout.setHorizontalGroup(
            panelBotonesFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCarteleras, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
            .addComponent(btnFacturar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelBotonesFacturasLayout.setVerticalGroup(
            panelBotonesFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesFacturasLayout.createSequentialGroup()
                .addComponent(btnCarteleras, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFacturar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panelBotonesFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addComponent(panelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotonesFacturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelcontenedor.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout panelcontenedorLayout = new javax.swing.GroupLayout(panelcontenedor);
        panelcontenedor.setLayout(panelcontenedorLayout);
        panelcontenedorLayout.setHorizontalGroup(
            panelcontenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 907, Short.MAX_VALUE)
        );
        panelcontenedorLayout.setVerticalGroup(
            panelcontenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelcontenedor))
            .addComponent(panelBarra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addComponent(panelBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelcontenedor)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public int tipo;
    int ocultarMenu = 0;
    private void btnCerrarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMenuMouseClicked
        // TODO add your handling code here:
        frmLogin login = new frmLogin();
        if (ocultarMenu == 0) {

            panelMenu.setSize(248, 614);
            panelMenu.setVisible(false);
            login.principal.panelMenu.setSize(248, 614);
            ocultarMenu = 1;
        } else {

            panelMenu.setVisible(true);
            btnFacturar.setSize(248, 67);
            login.principal.panelMenu.setSize(248, 614);

            ocultarMenu = 0;
        }
    }//GEN-LAST:event_btnCerrarMenuMouseClicked
    public int cerrar = 0;

    void cerrarjinternal() {
        try {
            proveedor.dispose();
        } catch (Exception e) {
        }
        try {
            producto.dispose();
        } catch (Exception e) {
        }
        try {
            rol.dispose();
        } catch (Exception e) {
        }
        try {
            persona.dispose();
        } catch (Exception e) {
        }
        try {
            horario.dispose();
        } catch (Exception e) {
        }
        try {
            Sala.dispose();

        } catch (Exception e) {
        }
        try {
            pelicula.dispose();
        } catch (Exception e) {
        }
        try {
            cartelera.dispose();
        } catch (Exception e) {
        }
        try {
            facturar.dispose();
        } catch (Exception e) {
        }
        try {
            logo.dispose();

        } catch (Exception e) {
        }
    }
    public fLogo logo;

    public void Mostrar() {
        if (cerrar == 1) {
            cerrarjinternal();
            if (pelicula == null || pelicula.isClosed()) {
                pelicula = new fPeliculas();
                panelcontenedor.add(pelicula);
                pelicula.setVisible(true);
                try {
                    pelicula.setMaximum(true);
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            if (cerrar == 2) {
                cerrarjinternal();
                if (producto == null || producto.isClosed()) {
                    producto = new fProductos();
                    panelcontenedor.add(producto);
                    producto.setVisible(true);
                    try {
                        producto.setMaximum(true);
                    } catch (PropertyVetoException ex) {
                        Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } else {
                if (cerrar == 3) {
                    cerrarjinternal();
                    if (proveedor == null || proveedor.isClosed()) {
                        proveedor = new fProveedores();
                        panelcontenedor.add(proveedor);
                        proveedor.setVisible(true);
                        try {
                            proveedor.setMaximum(true);
                        } catch (PropertyVetoException ex) {
                            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    }

                } else {
                    if (cerrar == 4) {
                        cerrarjinternal();
                        if (rol == null || rol.isClosed()) {
                            rol = new fRoles();
                            try {
                                rol.setMaximum(true);
                            } catch (Exception e) {
                            }
                            panelcontenedor.add(rol);
                            rol.setVisible(true);
                        }

                    } else {
                        if (cerrar == 5) {
                            cerrarjinternal();
                            if (persona == null || persona.isClosed()) {
                                persona = new fPersonas();

                                try {
                                    persona.setMaximum(true);
                                } catch (Exception e) {
                                }
                                panelcontenedor.add(persona);
                                persona.setVisible(true);
                            }
                        } else {
                            if (cerrar == 6) {
                                cerrarjinternal();
                                if (Sala == null || Sala.isClosed()) {
                                    Sala = new fSalas();

                                    try {
                                        Sala.setMaximum(true);
                                    } catch (Exception e) {
                                    }
                                    panelcontenedor.add(Sala);
                                    Sala.setVisible(true);
                                }
                            } else {
                                if (cerrar == 7) {
                                    cerrarjinternal();
                                    if (horario == null || horario.isClosed()) {
                                        horario = new fHorarios();
                                        horario.edicion = 0;
                                        horario.lectura();
                                        try {
                                            horario.setMaximum(true);
                                        } catch (Exception e) {
                                        }

                                        panelcontenedor.add(horario);

                                        horario.setVisible(true);
                                    }

                                } else {
                                    if (cerrar == 8) {
                                        cerrarjinternal();
                                        if (cartelera == null || cartelera.isClosed()) {
                                            cartelera = new fCartelera();

                                            try {
                                                cartelera.setMaximum(true);
                                            } catch (Exception e) {
                                            }

                                            panelcontenedor.add(cartelera);

                                            cartelera.setVisible(true);
                                        }

                                    } else {
                                        if (cerrar == 9) {
                                            cerrarjinternal();
                                            if (facturar == null || facturar.isClosed()) {
                                                facturar = new fFacturas();

                                                try {
                                                    facturar.setMaximum(true);
                                                } catch (Exception e) {
                                                }

                                                panelcontenedor.add(facturar);

                                                facturar.setVisible(true);
                                            }
                                        }

                                    }
                                }
                            }

                        }
                    }
                }
            }
        }
    }
    public fPeliculas pelicula;
    private void btnPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeliculasActionPerformed
        cerrar = 1;
        Mostrar();


    }//GEN-LAST:event_btnPeliculasActionPerformed
    public fProveedores proveedor;
    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        cerrar = 3;
        Mostrar();


    }//GEN-LAST:event_btnProveedoresActionPerformed
    public fProductos producto;
    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        cerrar = 2;
        Mostrar();

    }//GEN-LAST:event_btnProductosActionPerformed
    public fRoles rol;
    private void btnRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRolesActionPerformed
        // TODO add your handling code here:
        cerrar = 4;
        Mostrar();
    }//GEN-LAST:event_btnRolesActionPerformed
    public fPersonas persona;
    private void btnPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonasActionPerformed
        // TODO add your handling code here:
        cerrar = 5;
        Mostrar();

    }//GEN-LAST:event_btnPersonasActionPerformed

    private void btnOcultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOcultarMouseClicked
        // TODO add your handling code here:

        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnOcultarMouseClicked

    private void btncerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncerrarMouseClicked

        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(this, "Desea salir?", "Advertencia", JOptionPane.YES_NO_OPTION);
        if (res == 0) {
            System.exit(0);
        } else {

        }
    }//GEN-LAST:event_btncerrarMouseClicked

    int minimizar = 0;
    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        // TODO add your handling code here:
        if (minimizar == 0) {
            this.setExtendedState(MAXIMIZED_BOTH);
            btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/pestana-multiple.png")));
            minimizar = 1;
        } else if (minimizar == 1) {
            this.setSize(1158, 676);
            this.setLocationRelativeTo(null);
            minimizar = 0;
            btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/maximizar.png")));
        }
    }//GEN-LAST:event_btnMinimizarMouseClicked
    int x, y;
    private void panelBarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBarraMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panelBarraMousePressed

    private void panelBarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBarraMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_panelBarraMouseDragged
    public fSalas Sala;
    private void btnSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalasActionPerformed
        // TODO add your handling code here:
        cerrar = 6;
        Mostrar();
    }//GEN-LAST:event_btnSalasActionPerformed
    public fHorarios horario;
    private void btnHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHorariosActionPerformed
        // TODO add your handling code here:
        cerrar = 7;

        Mostrar();

    }//GEN-LAST:event_btnHorariosActionPerformed

    public fCartelera cartelera;
    private void btnCartelerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCartelerasActionPerformed
        // TODO add your handling code here:
        cerrar = 8;
        Mostrar();
    }//GEN-LAST:event_btnCartelerasActionPerformed
    public fFacturas facturar;
    private void btnFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturarActionPerformed
        // TODO add your handling code here:
        cerrar = 9;
        Mostrar();
    }//GEN-LAST:event_btnFacturarActionPerformed

    private void lblLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoMouseClicked
        // TODO add your handling code here:
        cerrarjinternal();

        if (logo == null || logo.isClosed()) {
            logo = new fLogo();

            try {
                logo.setMaximum(true);
            } catch (Exception e) {
            }

            panelcontenedor.add(logo);

            logo.setVisible(true);
        }

    }//GEN-LAST:event_lblLogoMouseClicked

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(this, "Desea cerrar sesion?", "Advertencia", JOptionPane.YES_NO_OPTION);
        if (res == 0) {
            cerrarjinternal();
            this.dispose();
            frmLogin f = new frmLogin();
            f.setVisible(true);
        } else {

        }

    }//GEN-LAST:event_lblSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCarteleras;
    private javax.swing.JLabel btnCerrarMenu;
    public javax.swing.JButton btnFacturar;
    public javax.swing.JButton btnHorarios;
    private javax.swing.JLabel btnMinimizar;
    private javax.swing.JLabel btnOcultar;
    public javax.swing.JButton btnPeliculas;
    public javax.swing.JButton btnPersonas;
    public javax.swing.JButton btnProductos;
    public javax.swing.JButton btnProveedores;
    public javax.swing.JButton btnRoles;
    public javax.swing.JButton btnSalas;
    private javax.swing.JLabel btncerrar;
    public javax.swing.JLabel lblID;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblSalir;
    public javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panelBarra;
    public javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelBotonesFacturas;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelLogo;
    public javax.swing.JPanel panelMenu;
    public javax.swing.JDesktopPane panelcontenedor;
    // End of variables declaration//GEN-END:variables

    private void setMaximumSize(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setMinimumSize(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
