/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unab.edu.sv.Formularios;

import com.unab.edu.sv.DAO.ClsSalas;
import com.unab.edu.sv.Entidades.Salas;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 14-ck0013lab
 */
public class fSalas extends javax.swing.JInternalFrame {

    /**
     * Creates new form fSalas
     */
    public fSalas() {
        initComponents();
        CargarTabla();
        ajustartabla();
        limpiar();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        lectura();
        tbSalas.setColumnSelectionAllowed(isSelected);
        tbSalas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        panelCRUD = new javax.swing.JPanel();
        lblCapacidad = new javax.swing.JLabel();
        txtCapacidad = new javax.swing.JTextField();
        lblNumerodeSala = new javax.swing.JLabel();
        txtNumerodeSala = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        TABLA = new javax.swing.JScrollPane();
        tbSalas = new javax.swing.JTable();
        lblEncabezado = new javax.swing.JLabel();
        btnLectura = new javax.swing.JLabel();

        panelFondo.setBackground(new java.awt.Color(0, 0, 0));

        panelCRUD.setBackground(new java.awt.Color(153, 255, 204));
        panelCRUD.setOpaque(false);

        lblCapacidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCapacidad.setForeground(new java.awt.Color(255, 255, 255));
        lblCapacidad.setText("CAPACIDAD");

        txtCapacidad.setBackground(new java.awt.Color(0, 0, 0));
        txtCapacidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCapacidad.setForeground(new java.awt.Color(255, 255, 255));
        txtCapacidad.setBorder(null);
        txtCapacidad.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCapacidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCapacidadKeyReleased(evt);
            }
        });

        lblNumerodeSala.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNumerodeSala.setForeground(java.awt.Color.white);
        lblNumerodeSala.setText("NUMERO DE SALA");

        txtNumerodeSala.setBackground(new java.awt.Color(0, 0, 0));
        txtNumerodeSala.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNumerodeSala.setForeground(new java.awt.Color(255, 255, 255));
        txtNumerodeSala.setBorder(null);
        txtNumerodeSala.setCaretColor(new java.awt.Color(255, 255, 255));
        txtNumerodeSala.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumerodeSalaKeyReleased(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(255, 255, 102));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setBorderPainted(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 255, 102));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setBorderPainted(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(255, 255, 102));
        btnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setBorderPainted(false);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCRUDLayout = new javax.swing.GroupLayout(panelCRUD);
        panelCRUD.setLayout(panelCRUDLayout);
        panelCRUDLayout.setHorizontalGroup(
            panelCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCRUDLayout.createSequentialGroup()
                .addGroup(panelCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCRUDLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(lblCapacidad))
                    .addGroup(panelCRUDLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(lblNumerodeSala))
                    .addGroup(panelCRUDLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(panelCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCRUDLayout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addGap(17, 17, 17)
                                .addComponent(btnEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiar))
                            .addGroup(panelCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNumerodeSala, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                .addComponent(txtCapacidad, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                .addComponent(jSeparator1)
                                .addComponent(jSeparator2)))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        panelCRUDLayout.setVerticalGroup(
            panelCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCRUDLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblCapacidad)
                .addGap(18, 18, 18)
                .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblNumerodeSala)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNumerodeSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(panelCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnEliminar)
                    .addComponent(btnGuardar))
                .addContainerGap())
        );

        tbSalas = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int collIndex){
                return false;
            }
        };
        tbSalas.setBackground(new java.awt.Color(0, 0, 0));
        tbSalas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbSalas.setForeground(java.awt.Color.white);
        tbSalas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbSalas.setCellSelectionEnabled(true);
        tbSalas.setGridColor(new java.awt.Color(0, 0, 0));
        tbSalas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSalasMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbSalasMouseReleased(evt);
            }
        });
        TABLA.setViewportView(tbSalas);

        lblEncabezado.setFont(new java.awt.Font("Algerian_R", 1, 60)); // NOI18N
        lblEncabezado.setForeground(new java.awt.Color(255, 255, 255));
        lblEncabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEncabezado.setText("SALAS");

        btnLectura.setForeground(new java.awt.Color(204, 255, 255));
        btnLectura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/lectura.png"))); // NOI18N
        btnLectura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLectura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLecturaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(lblEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(156, 156, 156)
                        .addComponent(btnLectura))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(TABLA, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelCRUD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLectura))
                    .addComponent(lblEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TABLA, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(panelCRUD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 875, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(11, 11, 11)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ajustartabla() {
        // Ocultar la columna del ID de la pelicula
        tbSalas.getColumnModel().getColumn(0).setMaxWidth(0);
        tbSalas.getColumnModel().getColumn(0).setMinWidth(0);
        tbSalas.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        tbSalas.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);

        //Centrar en texto del encabezado de la tabla
        DefaultTableCellRenderer render = (DefaultTableCellRenderer) tbSalas.getTableHeader().getDefaultRenderer();
        render.setHorizontalAlignment(JLabel.CENTER);
        DefaultTableCellRenderer al = new DefaultTableCellRenderer();
        al.setHorizontalAlignment(SwingConstants.CENTER);
        tbSalas.getColumnModel().getColumn(0).setCellRenderer(al);
        tbSalas.getColumnModel().getColumn(1).setCellRenderer(al);
        tbSalas.getColumnModel().getColumn(2).setCellRenderer(al);

    }

    void CargarTabla() {
        String TITULOS[] = {"ID", "CAPACIDAD", "NUMERO DE SALA"};
        ClsSalas sala = new ClsSalas();
        DefaultTableModel model = new DefaultTableModel(null, TITULOS);
        ArrayList<Salas> sal = sala.MostrarSalas();
        String filas[] = new String[4];
        for (var i : sal) {
            filas[0] = String.valueOf(i.idSala);
            filas[1] = String.valueOf(i.getCapacidad());
            filas[2] = String.valueOf(i.getNumero_Sala());
            model.addRow(filas);
        }
        tbSalas.setModel(model);

    }

    public void limpiar() {
        txtCapacidad.setText("");
        txtNumerodeSala.setText("");
        estado = 0;
        id = 0;

    }

    int estado = 0;
    int id = 0;
    int numerosala;
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (estado == 0) {

            if (txtCapacidad.getText() == "" || txtCapacidad.getText().isEmpty() || txtCapacidad.getText() == null) {
                JOptionPane.showMessageDialog(null, "Es necesario agregar Capacidad");
                txtCapacidad.requestFocus();
            } else if (txtNumerodeSala.getText() == "" || txtNumerodeSala.getText().isEmpty() || txtNumerodeSala.getText() == null) {
                JOptionPane.showMessageDialog(null, "Es necesario agregar Numero de Sala");
                txtNumerodeSala.requestFocus();
            } else {
                int contador = tbSalas.getRowCount();
                if (contador == 0) {
                    Salas sa = new Salas();
                    sa.setCapacidad(Integer.valueOf(txtCapacidad.getText()));
                    sa.setNumero_Sala(Integer.valueOf(txtNumerodeSala.getText()));
                    ClsSalas sala = new ClsSalas();
                    sala.GuardarSala(sa);
                    limpiar();
                    CargarTabla();
                    ajustartabla();
                }
                int contadorsala = 0;
                for (int i = 0; i <= tbSalas.getRowCount(); i++) {
                    String n = String.valueOf(tbSalas.getValueAt(i, 2));
                    int numero = Integer.valueOf(n);
                    if (numero == Integer.valueOf(txtNumerodeSala.getText())) {
                        i = tbSalas.getRowCount();
                    } else {
                        contadorsala++;
                    }
                    if (contadorsala == tbSalas.getRowCount()) {
                        Salas sa = new Salas();
                        sa.setCapacidad(Integer.valueOf(txtCapacidad.getText()));
                        sa.setNumero_Sala(Integer.valueOf(txtNumerodeSala.getText()));
                        ClsSalas sala = new ClsSalas();
                        sala.GuardarSala(sa);
                        limpiar();
                        CargarTabla();
                        ajustartabla();
                    } else {
                        JOptionPane.showMessageDialog(null, "Este numero de sala ya existe");
                    }
                }
            }
        } else if (estado == 1) {

            if (txtCapacidad.getText() == "" || txtCapacidad.getText().isEmpty() || txtCapacidad.getText() == null) {
                JOptionPane.showMessageDialog(null, "Es necesario agregar Capacidad");
                txtCapacidad.requestFocus();
            } else if (txtNumerodeSala.getText() == "" || txtNumerodeSala.getText().isEmpty() || txtNumerodeSala.getText() == null) {
                JOptionPane.showMessageDialog(null, "Es necesario agregar Numero de Sala");
                txtNumerodeSala.requestFocus();
            } else {
                if (numerosala == Integer.valueOf(txtNumerodeSala.getText())) {
                    Salas sal = new Salas();
                    sal.setIdSala(id);
                    sal.setCapacidad(Integer.valueOf(txtCapacidad.getText()));
                    sal.setNumero_Sala(Integer.valueOf(txtNumerodeSala.getText()));
                    ClsSalas salas = new ClsSalas();
                    salas.ActualizarSala(sal);
                    CargarTabla();
                    ajustartabla();
                } else {
                    JOptionPane.showMessageDialog(null, "No se puede realizar este cambio");
                }
            }
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        Salas S = new Salas();
        ClsSalas cls = new ClsSalas();
        S.setIdSala(id);
        cls.EliminarSala(S);
        CargarTabla();
        ajustartabla();
        limpiar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tbSalasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSalasMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tbSalasMouseClicked

    private void btnLecturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLecturaMouseClicked
        // TODO add your handling code here:
        lectura();
    }//GEN-LAST:event_btnLecturaMouseClicked

    private void txtCapacidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCapacidadKeyReleased
        // TODO add your handling code here:
        try {
            int capacidad = Integer.parseInt(txtCapacidad.getText());
        } catch (Exception e) {
            txtCapacidad.setText("");
        }
    }//GEN-LAST:event_txtCapacidadKeyReleased

    private void txtNumerodeSalaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumerodeSalaKeyReleased
        // TODO add your handling code here:
        try {
            int numero = Integer.parseInt(txtNumerodeSala.getText());
        } catch (Exception e) {
            txtNumerodeSala.setText("");
        }
    }//GEN-LAST:event_txtNumerodeSalaKeyReleased

    private void tbSalasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSalasMouseReleased
        // TODO add your handling code here:
        int fila = tbSalas.getSelectedRow();
        id = Integer.valueOf(String.valueOf(tbSalas.getValueAt(fila, 0)));
        String Capaci = String.valueOf(tbSalas.getValueAt(fila, 1));
        String numeroS = String.valueOf(tbSalas.getValueAt(fila, 2));
        estado = 1;
        txtCapacidad.setText(Capaci);
        txtNumerodeSala.setText(numeroS);
        numerosala = Integer.valueOf(numeroS);
    }//GEN-LAST:event_tbSalasMouseReleased

    int edicion = 0;

    void lectura() {
        if (edicion == 0) {
            panelCRUD.setVisible(false);
            btnLectura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/editar.png")));
            edicion = 1;
        } else {
            btnLectura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/lectura.png")));
            panelCRUD.setVisible(true);
            edicion = 0;
        }
        limpiar();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane TABLA;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel btnLectura;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCapacidad;
    private javax.swing.JLabel lblEncabezado;
    private javax.swing.JLabel lblNumerodeSala;
    private javax.swing.JPanel panelCRUD;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JTable tbSalas;
    private javax.swing.JTextField txtCapacidad;
    private javax.swing.JTextField txtNumerodeSala;
    // End of variables declaration//GEN-END:variables
}
